### ISSUE TITLE
Registering redirect from Login Page fails

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#95] opened 2022-12-15 13:49 UTC
**Describe the bug**
Try to register from the link provided in the login form

**Steps To Reproduce**
1 - Go to Login Page and click on the "Register" button
2 - Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207875422-dc273b7b-b1b6-4ca3-9732-40c3d7a9b4a4.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:15
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/42

**Closed as completed by Innos** 2022-12-16 13:15 UTC
Labels: Duplicate
