### ISSUE TITLE
Scroll of the page does not work when click in code section

### ISSUE THREAD

**Issue by DesislavaTopuzakova** [SoftUni-Internal/hackathon-issues#54] opened 2022-12-15 12:51 UTC
**Describe the bug**
Scroll of the page does not work when click in code section

**Steps To Reproduce**
1. Click on field to enter source code
2. Try to scroll with the mouse
Result: Page scroll does not work

**Screenshots**

![image](https://user-images.githubusercontent.com/34713586/207863690-0c1e5f7f-eb1b-4dc8-84ce-c276623f631c.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:33
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/4

**Closed as completed by Innos** 2022-12-16 13:33 UTC
Labels: Duplicate
