### ISSUE TITLE
Results page has no data

### ISSUE THREAD

**Issue by Boyan-Apostolov** [SoftUni-Internal/hackathon-issues#17] opened 2022-12-15 12:19 UTC
**Describe the bug**
When opening the results page, we see no info (a white empty page)

**Steps To Reproduce**
Open a task, click results

**Screenshots**
![image](https://user-images.githubusercontent.com/58187770/207857693-46324d01-75c6-459c-90be-836fbc3427e7.png)
![image](https://user-images.githubusercontent.com/58187770/207857716-fd600e16-45f4-4135-b1eb-6d108ec5acae.png)

**Comment by Innos** [comment] 2022-12-16 13:43
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/5

**Closed as completed by Innos** 2022-12-16 13:43 UTC
Labels: Duplicate
