### ISSUE TITLE
Profile update

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#38] opened 2022-12-15 12:37 UTC
After click on update button in profile page it directly redirects to home. No edit button and all in the profile is disabled for editing.

**Comment by Innos** [comment] 2022-12-16 13:40
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/7

**Closed as completed by Innos** 2022-12-16 13:40 UTC
Labels: Duplicate

**Comment by PetkoAndreev** [comment] 2022-12-16 20:21
Agree, but as a suggestion it'll be good to add edit functionality or a possibility to remove contest or something similar as a logic, because in the current situation the Update button is pretty much useless.
