### ISSUE TITLE
Submissions page is showint data for other participants 

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#62] opened 2022-12-15 12:56 UTC
**Describe the bug**
When we open https://judgesoftuniorg.ml/submissions we can observe other participants' solutions.  This is not allowed in the current ly working system

**Steps To Reproduce**
1 - Open https://judgesoftuniorg.ml/submissions
2 - Invite others to submit
3  - Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207864317-7596aa78-3fb2-418b-a9b4-f7ed0baf4e9c.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:31
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/16

**Closed as completed by Innos** 2022-12-16 13:31 UTC
Labels: Duplicate
