### ISSUE TITLE
Remaining Time bugs when window is inactive.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#112] opened 2022-12-15 14:31 UTC
**Describe the bug**
When leaving a contest window inactive for some time, the Remaining Time gets bugged out. 

**Steps To Reproduce**
1. Open Contest
2. Leave window inactive

**Screenshots**
Inactive window timer: 
![image](https://user-images.githubusercontent.com/24556064/207886889-5346ea0e-5134-453e-98ac-9b3d6f380a7f.png)
Real timer: 
![image](https://user-images.githubusercontent.com/24556064/207886989-71902216-bd09-4f6f-b973-c1d9d03e5556.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 12:57
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/107

**Closed as completed by Innos** 2022-12-16 12:57 UTC
Labels: Duplicate
