### ISSUE TITLE
"Active Contests" remaing time is not the same as the contest's actual remaining time.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#83] opened 2022-12-15 13:33 UTC
**Describe the bug**
In the Main Page's "Active Contests" section, the remaining time of the contest is not the same as the remaining time form the contest's page.

**Steps To Reproduce**
1. Open Judge
2. Scroll to "Active Contests"
3. Open contest to check the remaining time shown there aswell.

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207871917-9745d59f-f61c-4982-abe4-18625d1a14ec.png)
![image](https://user-images.githubusercontent.com/24556064/207872059-e84782b2-0cc1-4434-820f-747a3b54b342.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:17
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/68

**Closed as completed by Innos** 2022-12-16 13:17 UTC
Labels: Duplicate, works as intended
