### ISSUE TITLE
Tasks - total result

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#49] opened 2022-12-15 12:46 UTC
Total result doesn't change until refresh of the page:
![image](https://user-images.githubusercontent.com/77919922/207862606-9304fb30-6018-4e21-94e0-2a69ac400392.png)
![image](https://user-images.githubusercontent.com/77919922/207862626-98d4b8e1-a3c4-4242-8c2d-dd0075d74545.png)

**Comment by Innos** [comment] 2022-12-16 13:38
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/20

**Closed as completed by Innos** 2022-12-16 13:38 UTC
Labels: Duplicate
