### ISSUE TITLE
Compete - Practice buttons visualization

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#172] opened 2023-09-26 14:33 UTC
It'll be better if the style and fulfillement of the buttons is equalified:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/eea4ac6c-9fe5-4187-8396-fe9cce622b5e)

**Comment by Innos** [comment] 2023-09-28 14:59
Stylization choices are pretty subjective, the current judge also uses a different color for the Compete button, making it stand out among the others, so I see no problem with a stylization choice that accomplishes the same here. I'm closing this issue as working as intended.

**Closed as completed by Innos** 2023-09-28 14:59 UTC
Labels: works as intended, UX/UI, Recommendation
