### ISSUE TITLE
Contest Score - null

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#114] opened 2022-12-15 14:32 UTC
When open a contest - https://judgesoftuniorg.ml/contests/2602/practice#1 in the score there are null/100 instead of 0/100:
![image](https://user-images.githubusercontent.com/77919922/207887164-946e3382-aaac-4a07-b581-4853d825272f.png)

**Comment by Innos** [comment] 2022-12-16 12:56
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/88

**Closed as completed by Innos** 2022-12-16 12:56 UTC
Labels: Duplicate
