### ISSUE TITLE
Merge text

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#80] opened 2022-12-15 13:26 UTC
**Describe the bug**
In the page submissions, the time when the solution was uploaded and the username are merged

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207870202-964c2314-82f2-41e4-ab47-a2a963a74a0e.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:18
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/22

**Closed as completed by Innos** 2022-12-16 13:18 UTC
Labels: Duplicate
