### ISSUE TITLE
Submissions text formatting error

### ISSUE THREAD

**Issue by Boyan-Apostolov** [SoftUni-Internal/hackathon-issues#65] opened 2022-12-15 13:00 UTC
**Describe the bug**
then username is touching the 'n minutes ago' text

**Steps To Reproduce**
Open submissions page

**Screenshots**
![image](https://user-images.githubusercontent.com/58187770/207865224-7aee14a3-43c4-48ec-a574-38cba86de22c.png)

**Comment by Innos** [comment] 2022-12-16 13:31
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/22

**Closed as completed by Innos** 2022-12-16 13:31 UTC
Labels: Duplicate
