### ISSUE TITLE
Can's submit when there is a previous solutions with infinity loop

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#123] opened 2022-12-15 14:54 UTC
**Describe the bug**

I submit infinity loop and then tried to submit secon correct solution, but it didn't commit
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/72857425/207892255-d6892f8a-1b85-4b80-9c18-eae972420887.png)
![image](https://user-images.githubusercontent.com/72857425/207892194-5add4a1e-fc4c-44f9-aec1-a4f3457835c4.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 12:53
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/43

**Closed as completed by Innos** 2022-12-16 12:53 UTC
Labels: Duplicate
