### ISSUE TITLE
Refreshing after change Contest category

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#186] opened 2023-09-26 15:20 UTC
It's recommendation - after each click/change of contest category the page is refreshed and blue loading circle is showed. It can be changed like navigating between the tasks in a particular contest.

**Comment by Innos** [comment] 2023-09-28 15:05
I imagine it would be a poor technical choice to do this. Problems in the contest can be preloaded I would guess, as there is a reasonable expectation that they would be viewed, on the other hand preloading paginated categories, that might never be visited sounds counterproductive.

Closing this issue as working as intended

**Closed as completed** 2023-09-28 15:14 UTC
Labels: works as intended, functional, Recommendation
