### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#23] opened 2022-12-15 12:27 UTC
**Describe the bug**

Once you open to view the details of the uploaded solution, you cannot go back
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207859092-60ed308e-66f5-4eb0-a674-330ff7dc4e52.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:19
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:19 UTC
Labels: Duplicate
