### ISSUE TITLE
Symmetry

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#97] opened 2022-12-15 13:50 UTC
**Describe the bug**

In section contest there is no symmetry to the current races in the section
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207875266-99ee86d7-c446-4e94-a890-d5b0efd5afb7.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:14
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/90

**Closed as completed by Innos** 2022-12-16 13:14 UTC
Labels: Duplicate
