### ISSUE TITLE
Changing submission ID from link opens a blank page.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#144] opened 2022-12-15 21:28 UTC
**Describe the bug**
When changing the ID of a submission with random characters from the url returns a blank page

**Steps To Reproduce**
Change submission ID

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207970797-90e02a6f-3a06-4f74-b31d-257551be3a53.png)

**Comment by Innos** [comment] 2022-12-16 12:39
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/132

**Closed as completed** 2022-12-16 12:47 UTC
Labels: Duplicate
