### ISSUE TITLE
Submission details page fails periodically

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#55] opened 2022-12-15 12:52 UTC
**Describe the bug**
When we click on the Details button sometimes a blank page appears

**Steps To Reproduce**
1 - Go to the "Submissions" page
2 - Click several times on "Details" button for different submissions

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207863665-684fe7de-9a8d-469b-9741-d1e6d0afe839.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:33
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18

**Closed as completed by Innos** 2022-12-16 13:33 UTC
Labels: Duplicate
