### ISSUE TITLE
Register - infinite loading

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#40] opened 2022-12-15 12:39 UTC
When Logout and click on Register button it loads infinitely and it's unable to register.
![image](https://user-images.githubusercontent.com/77919922/207861317-2a2e65df-f002-4c70-8bd2-f2f747d99e98.png)

**Comment by Innos** [comment] 2022-12-16 13:20
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/31

**Closed as completed by Innos** 2022-12-16 13:20 UTC
Labels: Duplicate
