### ISSUE TITLE
Filtering visualization

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#164] opened 2023-09-26 14:12 UTC
Filter and clear filters works, but just the visual part above the button Clear Filter remains:
Filter applied:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/3f357e7c-8de2-4a8b-8b2f-7f3fef26607f)

Filter cleared:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/941c125e-0330-4b5f-90b3-ff8d4ee5b2fd)

**Comment by Innos** [comment] 2023-09-27 12:17
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/158

**Closed as completed** 2024-06-17 11:22 UTC
Labels: Duplicate, UX/UI, filters
