### ISSUE TITLE
Sorting and Status acting unintuitively.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#145] opened 2022-12-15 21:58 UTC
**Describe the bug**
In Contests page:
When clicking any button except the default one while it's selected brings it back to the default position, but when clicking the default choice a second time, it does not do anything.

**Steps To Reproduce**
1. Click non-default choice
2. Click non-default choice again and it returns to default
/
1. Click default choice from a non-default
2. Click default choice again and it does not select the previously selected

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207975752-781ec01f-0c15-4817-a7dc-6005955b8d71.png)

**Comment by Innos** [comment] 2022-12-16 12:41
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/96

**Closed as completed** 2022-12-16 12:47 UTC
Labels: Duplicate
