### ISSUE TITLE
Contest pages - not available go to first/last page

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#185] opened 2023-09-26 15:15 UTC
On the main page with the contests it's not possible to navigate to the first or to the last page. Only can navigate page by page:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/dbaf894b-10da-47ae-b617-b064fc89a2a2)

**Comment by Innos** [comment] 2023-09-27 14:55
@PetkoAndreev Can you provide more details like whether you were logged in, link to the page, specify which pagination, settings if any applied and which browser and version, since I cannot seem to reproduce it.

**Comment by Innos** [comment] 2023-09-27 15:10
After Discussion it seems it is a recommendation for the dots to be clickable and to have first/last page buttons like this:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/1db09814-c2d0-4e8c-a61b-19fc403775b9)
However since this pagination always shows the buttons for the first and last page, first/last page buttons seem redundant.

To allow the dots to work as in the current Judge was also already recommended here https://github.com/SoftUni-Internal/hackathon-issues/issues/182 , so I'm closing this as redundant.

**Closed as completed by Innos** 2023-09-27 15:10 UTC
Labels: works as intended, functional, pagination
