### ISSUE TITLE
Clicking on register opens blank page.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#78] opened 2022-12-15 13:22 UTC
**Describe the bug**
When clicking on the "Register" button, it opens a blank page, but with Judge header and footer. It also has link:
"https://judgesoftuniorg.ml/login/undefinedundefined/register".

**Steps To Reproduce**
1. Open "Login" page.
2. Click on "Register" from the Login form

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207870504-8856b987-922a-4119-8cbb-2bbfe4bbe389.png)

![image](https://user-images.githubusercontent.com/24556064/207869635-4c34a71c-dcc0-4bcf-8114-8a77ea92c9a5.png)

**Comment by Innos** [comment] 2022-12-16 13:21
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/42

**Closed as completed by Innos** 2022-12-16 13:21 UTC
Labels: Duplicate
