### ISSUE TITLE
Contest - click Practice not open the contest

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#111] opened 2022-12-15 14:26 UTC
When click on Practice of the contest for Python Web Exams it open blank page with url (https://judgesoftuniorg.ml/contests/undefined/undefined#1):
![image](https://user-images.githubusercontent.com/77919922/207885798-b318c549-785d-4069-909a-5dbebb95f6f7.png)

**Comment by Innos** [comment] 2022-12-16 13:02
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/27

Connected issue https://github.com/SoftUni-Internal/hackathon-issues/issues/113

**Closed as completed by Innos** 2022-12-16 13:02 UTC
Labels: Duplicate
