### ISSUE TITLE
When we click on results a new tab is opened with no information

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#13] opened 2022-12-15 12:12 UTC
**Describe the bug**
On clicking the results button, a new page with no contents is opened. On clicking the back button in the left upper corner, the url is changed and but the contents for the page with the given url are not present. We have to click refresh to appear.

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207856066-55a428c1-9c86-47f6-a16c-37e39977c750.png)
![image](https://user-images.githubusercontent.com/86721304/207856097-57c3b7bd-dc4c-4e8a-b740-fdf343b8565c.png)
![image](https://user-images.githubusercontent.com/86721304/207856127-24d63cf7-e20f-4d51-a36a-ecd71d96e485.png)

**Additional context**
The first image is after clicking the results button.
The second is when we click the back one.
The third shows the page contents that are visible after a refresh

**Comment by Innos** [comment] 2022-12-16 13:43
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/5

**Closed as completed by Innos** 2022-12-16 13:43 UTC
Labels: Duplicate
