### ISSUE TITLE
Old submission errors stay even after changing task.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#140] opened 2022-12-15 19:54 UTC
**Describe the bug**
After getting a submission error and changing task, the submission error stays.

**Steps To Reproduce**
1. Open task
2. Get error
3. Change task

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207954247-e97845d0-e3f1-4f56-b645-fe47175ec02e.png)
![image](https://user-images.githubusercontent.com/24556064/207954281-1bc17ce2-51a1-4e4a-94c6-05006eebd5ff.png)

**Additional context**
Removed "disable" class from button for test purposes.

**Comment by kalin729** [comment] 2022-12-16 12:45
@Innos When you get an error message and switch the tasks, the message is still visible. For example, I get the message on Task 1 and then switch to Task 2, the message is still visible. I'm not sure if it should be like that or not.

**Comment by Innos** [comment] 2022-12-16 13:54
I just checked, the time until submit delay is global for the contest and shared among the problems, which is as it should be. So it is correct that you should not be able to submit in another problem, right after submitting on the first. If there is more info to this issue, please provide it, otherwise I'm closing this as works as intended

**Comment by Innos** [comment] 2022-12-16 14:50
Cleared it up with kalin729, it works as intended, closing the issue

**Closed as completed** 2022-12-16 14:49 UTC
Labels: works as intended
