### ISSUE TITLE
Cannot load details when I have points

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#71] opened 2022-12-15 13:05 UTC
**Describe the bug**
Cannot see the details page when I get points 

**Steps To Reproduce**
After reload they show up

**Screenshots**

![image](https://user-images.githubusercontent.com/72857425/207866163-f0c58b73-0ef3-4954-abf7-4d82189e8d23.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:24
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18

**Closed as completed by Innos** 2022-12-16 13:24 UTC
Labels: Duplicate
