### ISSUE TITLE
Submissions - navigates between the tasks

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#48] opened 2022-12-15 12:44 UTC
When navigates between the tasks the submissions stays from the previous one:
![image](https://user-images.githubusercontent.com/77919922/207862377-c240e544-3227-4656-a51c-23f4849f0df5.png)

**Comment by Innos** [comment] 2022-12-16 13:39
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/37

**Closed as completed by Innos** 2022-12-16 13:39 UTC
Labels: Duplicate
