### ISSUE TITLE
Profile submissions

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#36] opened 2022-12-15 12:36 UTC
When open a profile it shows default 5 submissions no matter if I have or not submissions the number doesn't change.
![image](https://user-images.githubusercontent.com/77919922/207860867-07489a96-7853-4558-a310-edbf318c39af.png)

**Comment by Innos** [comment] 2022-12-16 13:41
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/2

**Closed as completed by Innos** 2022-12-16 13:41 UTC
Labels: Duplicate
