### ISSUE TITLE
Submission details page not opening (staying blank)

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#94] opened 2022-12-15 13:46 UTC
**Describe the bug**
When we click on "Details" for a given submission there is a chance we get this page

**Steps To Reproduce**
1 - Go to https://judgesoftuniorg.ml/submissions
2 - Click a few times on the "Details" button of random submissions

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207874462-edfe73bb-c106-47ac-9bad-f9dbc7ddda72.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:16
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18

**Closed as completed by Innos** 2022-12-16 13:16 UTC
Labels: Duplicate
