### ISSUE TITLE
Other people submissions

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#57] opened 2022-12-15 12:53 UTC
When try to open some other user's submission it just opens a blank page - no info that it's not permitted or to just open user's own submission like in the old judge:
![image](https://user-images.githubusercontent.com/77919922/207864039-0d7d7329-9cbc-45ea-be65-8d3edef8d172.png)

**Comment by Innos** [comment] 2022-12-16 13:32
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/16

**Closed as completed by Innos** 2022-12-16 13:32 UTC
Labels: Duplicate

**Comment by PetkoAndreev** [comment] 2022-12-16 20:25
I think that this is not a duplication, because the colleague in the issue #16 mention that it's possible to open and see other users source code. I'm pointing to the opposite that this is not possible.
