### ISSUE TITLE
Back functionality

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#12] opened 2022-12-15 12:11 UTC
When pressing Ctrl + back arrow in the browser the functionality works and redirects to the previous page on a new tab, but as I mention on another issue only back arrow doesn't work.

**Comment by Innos** [comment] 2022-12-16 13:26
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:26 UTC
Labels: Duplicate
