### ISSUE TITLE
Joining a contest opens a blank page.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#105] opened 2022-12-15 14:05 UTC
**Describe the bug**
On some occasions, when joining a contest, it opens a blank page with the link: 
"https://judgesoftuniorg.ml/contests/undefined/undefined#1".

**Steps To Reproduce**
1. Go to "Contests" page
2. Join a contest

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207881210-4265e0ba-ec50-4372-ab81-8bf1da651454.png)

**Comment by Innos** [comment] 2022-12-16 13:08
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/27

**Closed as completed by Innos** 2022-12-16 13:08 UTC
Labels: Duplicate
