### ISSUE TITLE
Glitch when trying to practice a contest when not logged in

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#81] opened 2022-12-15 13:31 UTC
**Describe the bug**
When we click on practice when we are not logged in, we are prompted to do so. In case we are willing to go back, the navigation doesn't seem to work

**Steps To Reproduce**
1 - Log out
2 - Go to https://judgesoftuniorg.ml/contests
3 - Click on "Practice" on a random contest
4 - Try to go back when the login form appears

**Screenshots**

**Additional context**
We need to click on the contests button to be able to go back

**Comment by Innos** [comment] 2022-12-15 16:36
Same as https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Comment by Innos** [comment] 2022-12-16 13:18
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:18 UTC
Labels: Duplicate
