### ISSUE TITLE
Browser button for back does not work

### ISSUE THREAD

**Issue by DesislavaTopuzakova** [SoftUni-Internal/hackathon-issues#67] opened 2022-12-15 13:00 UTC
**Describe the bug**
When enter details of the submission and try to get back with the browser back button does not work.

**Steps To Reproduce**
1. Enter in details of the submission.
2. Click Back button in the browser.

Result: Does not go back to the previous page.

**Screenshots**
![image](https://user-images.githubusercontent.com/34713586/207865361-8a5cf16a-03ba-4de6-89e1-b0bad632e6ff.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:27
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:27 UTC
Labels: Duplicate
