### ISSUE TITLE
Contest - Results

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#117] opened 2022-12-15 14:39 UTC
When click on the Results in the contest (left sidebar) it navigates to a blank page with URL - 
 https://judgesoftuniorg.ml/contests/3093/practice/results/simple. Also currently is not possible to see other participants results as were in the old judge in the contest page.

**Comment by Innos** [comment] 2022-12-16 12:55
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/5

**Closed as completed by Innos** 2022-12-16 12:55 UTC
Labels: Duplicate
