### ISSUE TITLE
Submissions details page doesnt work correctly

### ISSUE THREAD

**Issue by Boyan-Apostolov** [SoftUni-Internal/hackathon-issues#21] opened 2022-12-15 12:23 UTC
**Describe the bug**
When I open the details of someones submissions, sometimes it works, sometimes it doesnt. I have attatched a video

**Steps To Reproduce**
[screen-capture.webm](https://user-images.githubusercontent.com/58187770/207858146-d9e75697-7104-4223-8071-94e989c82c1d.webm)

**Screenshots**
(see attached video)

**Comment by Innos** [comment] 2022-12-16 13:42
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18

**Closed as completed by Innos** 2022-12-16 13:42 UTC
Labels: Duplicate
