### ISSUE TITLE
Click on submission task name leads to undefined

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#77] opened 2022-12-15 13:21 UTC
**Describe the bug**
When we observe submissions and click on the name of the task that belongs to the submission we notice it leads to an undefined page

**Steps To Reproduce**
1 - Go to the submissions page
2 - Pick a submission and click on the task name
3 - Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207869594-55d01767-e4e9-4893-9bb6-8e8ed8c72fed.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:22
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/41

**Closed as completed by Innos** 2022-12-16 13:22 UTC
Labels: Duplicate
