### ISSUE TITLE
Login form - navigation to forgotten password

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#45] opened 2022-12-15 12:42 UTC
When click to Forgotten password from login form it navigates to an empty page:
![image](https://user-images.githubusercontent.com/77919922/207861935-1c2b64f4-eab3-457a-a054-727c621ad508.png)

**Comment by Innos** [comment] 2022-12-16 13:40
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/28

**Closed as completed by Innos** 2022-12-16 13:40 UTC
Labels: Duplicate
