### ISSUE TITLE
After navigate back from results

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#34] opened 2022-12-15 12:35 UTC
**Describe the bug**
There is a problem when we try to navigate back from results to the contest

**Steps To Reproduce**

We have to refresh to see contest again

**Screenshots**

![image](https://user-images.githubusercontent.com/72857425/207860507-3b6e9ef1-27a8-4c71-8394-677c6986a1e4.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:41
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:41 UTC
Labels: Duplicate
