### ISSUE TITLE
Forgotten Password Functionality not responding

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#84] opened 2022-12-15 13:33 UTC
**Describe the bug**
When we click on the "Forgotten Password" button, a redirection to https://judgesoftuniorg.ml/Account/ExternalNotify takes place with nothing else happening

**Steps To Reproduce**
1 - Go to the login page
2 - Click on "Forgotten Password"
3 - Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207872075-5b3345a4-cab3-4c6f-b0ad-5dd92e419c63.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:16
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/28

**Closed as completed by Innos** 2022-12-16 13:16 UTC
Labels: Duplicate
