### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#76] opened 2022-12-15 13:21 UTC
**Describe the bug**
Pressing the result button under the tasks opens a blank page

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207869273-7e5798e9-5d21-4b4d-a851-373b3273fb4c.png)
![image](https://user-images.githubusercontent.com/74661739/207869506-10fe5183-c677-4540-892b-32b02cee6e38.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 11:50
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/5

**Closed as completed** 2022-12-16 13:22 UTC
Labels: Duplicate
