### ISSUE TITLE
button details

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#99] opened 2022-12-15 13:53 UTC
**Describe the bug**
It doesn't work every time. Sometimes it sends you to a blank page

**Steps To Reproduce**

**Screenshots**

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:12
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18, also very poor description, that does not give enough information.

**Closed as completed by Innos** 2022-12-16 13:12 UTC
Labels: Duplicate, invalid
