### ISSUE TITLE
Navigation in other contests does not work

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#29] opened 2022-12-15 12:32 UTC
**Describe the bug**
I opened another exam in practice mode (https://judgesoftuniorg.ml/contests/1701/practice#1). On clicking the back button no action is observed. The same happened for https://judgesoftuniorg.ml/contests/472/compete#1

**Steps To Reproduce**
Start the hackaton. Navigate to https://judgesoftuniorg.ml/contests?category=59&page=1 and start practicing a random contest

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207859950-58ec8b7a-ee4c-4ba7-85e5-e2cd744ff2d6.png)

**Additional context**

**Comment by Innos** [comment] 2022-12-16 13:42
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3

**Closed as completed by Innos** 2022-12-16 13:42 UTC
Labels: Duplicate
